### ISSUE TITLE
跳转过去是否能把标题显示出来

### ISSUE THREAD

**Issue by heheda123123** [gxr404/github-md-toc#2]
比如任意点一个标题，会如下显示，页面最上面直接就是内容
![image](https://github.com/user-attachments/assets/c8c600f3-4811-4951-bb41-647e7174cfcb)
如果能往上面一点，把标题也显示出来就更好了
![image](https://github.com/user-attachments/assets/abcd5684-548a-48a6-8017-2d19d2387041)
感谢老哥开发这么好用的插件
个人意见

**Comment by gxr404** [comment]
已优化，v0.0.6 已发布到chrome store
